sudo: required
services:
    - docker

before_install:
    - docker build -t rogerloh/docker-react -f Dockerfile.dev .

script:
    - docker run rogerloh/docker-react npm run test -- --env=jsdom --watchAll=false  --coverage